get: # /roles
  tags:
    - entity
  summary: Get all roles
  description: ''
  security:
    - BearerAuth: []
  parameters:
    - in: query
      name: onlyMember
      type: number
      description: using for getting only member roles
      enum:
        - 1
      example: 1
  responses:
    '200':
      description: successful operation
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  $ref: './schemas.yml#/model'
    '401':
      $ref: '../../schemas/response-error.yml#/401'
    '403':
      $ref: '../../schemas/response-error.yml#/403'
    '404':
      $ref: '../../schemas/response-error.yml#/404'
    '412':
      $ref: '../../schemas/response-error.yml#/412'
    '500':
      $ref: '../../schemas/response-error.yml#/500'

post: # /roles
  tags:
    - entity
  summary: Create a entity
  description: ''
  security:
    - BearerAuth: []
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: './schemas.yml#/createRoleBody'
  responses:
    '200':
      description: successful operation
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                $ref: './schemas.yml#/model'
    '401':
      $ref: '../../schemas/response-error.yml#/401'
    '403':
      $ref: '../../schemas/response-error.yml#/403'
    '404':
      $ref: '../../schemas/response-error.yml#/404'
    '412':
      $ref: '../../schemas/response-error.yml#/412'
    '500':
      $ref: '../../schemas/response-error.yml#/500'
