model:
  type: object
  properties:
    $ref: '#/fields'

updateRoleBody:
  type: object
  properties:
    name:
      $ref: '#/fields/name'
    permissions:
      $ref: '#/fields/permissions'

createRoleBody:
  type: object
  required:
    - name
  properties:
    name:
      $ref: '#/fields/name'
    permissions:
      $ref: '#/fields/permissions'

permission:
  type: object
  schema:
    no:
      type: string
      description: number of permissions. it's used to order
    code:
      type: string
      description: permission code
    name:
      type: string
      description: permission name

fields:
  id:
    type: string
    description: user id
  name:
    type: string
    description: Role name
  permissions:
    type: array
    description: array of permission codes
    items:
      type: string
      description: Permission code
  updatedBy:
    type: string
    description: Updated by user id
  createdAt:
    type: string
    format: date-time
  updatedAt:
    type: string
    format: date-time
