exports.STATUS = {
    ACTIVE: 'active',
    // PENDING: 'pending', // chờ verify email - tạm thời không sử dụng, vì admin sẽ tạo account ở trạng thái active luôn
    INACTIVE: 'inactive', // hết thời gian bảo lưu
    // BLOCKED: 'blocked', // vì lý do nào đó không cho hoạt động nữa - tạm thời không sử dụng, vì chưa có nhu cầu
    DELETED: 'deleted',
    PENDING: 'pending',
}

exports.ACCOUNT_TYPE = {
    PASSWORD: 'password',
    GOOGLE: 'google',
}

exports.GENDER = {
    MALE: 'male',
    FEMALE: 'female',
    UNISEX: 'unisex',
}


exports.UNIVERSITY = {
    1: 'other',
    2: 'VNU',
    3: 'UEL',
    4: 'EUH',
    5: 'BA',
    6: 'AOF',
    7: 'NEU',
    8: 'FTU',
}

exports.CITY = {
    1: 'Hà Nội',
    2: 'TP Hồ Chí Minh',
    3: 'Hải Phòng',
    4: 'Đà Nẵng',
    5: 'Hà Giang',
    6: 'Cao Bằng',
    7: 'Lai Châu',
    8: 'Lào Cai',
    9: 'Tuyên Quang',
    10: 'Lạng Sơn',
    11: 'Bắc Kạn',
    12: 'Thái Nguyên',
    13: 'Yên Bái',
    14: 'Sơn La',
    15: 'Phú Thọ',
    16: 'Vĩnh Phúc',
    17: 'Quảng Ninh',
    18: 'Bắc Giang',
    19: 'Bắc Ninh',
    21: 'Hải Dương',
    22: 'Hưng Yên',
    23: 'Hòa Bình',
    24: 'Hà Nam',
    25: 'Nam Định',
    26: 'Thái Bình',
    27: 'Ninh Bình',
    28: 'Thanh Hóa',
    29: 'Nghệ An',
    30: 'Hà Tĩnh',
    31: 'Quảng Bình',
    32: 'Quảng trị',
    33: 'Thừa Thiên Huế',
    34: 'Quảng Nam',
    35: 'Quảng Ngãi',
    36: 'Kontum',
    37: 'Bình Định',
    38: 'Gia Lai',
    39: 'Phú Yên',
    40: 'Đắk Lắk',
    41: 'Khánh Hòa',
    42: 'Lâm Đồng',
    43: 'Bình Phước',
    44: 'Bình Dương',
    45: 'Ninh Thuận',
    46: 'Tây Ninh',
    47: 'Bình Thuận',
    48: 'Đồng Nai',
    49: 'Long An',
    50: 'Đồng Tháp',
    51: 'An Giang',
    52: 'Bà Rịa – Vũng Tàu',
    53: 'Tiền Giang',
    54: 'Kiên Giang',
    55: 'Cần Thơ',
    56: 'Bến Tre',
    57: 'Vĩnh Long',
    58: 'Trà Vinh',
    59: 'Sóc Trăng',
    60: 'Bạc Liêu',
    61: 'Cà Mau',
    62: 'Điện Biên',
    63: 'Đắk Nông',
    64: 'Hậu Giang',
}
