openapi: '3.0.3'
info:
  description: 'This is a sample server. For this sample, you can use the api key to test the authorization.'
  version: 1.0.0
  title: BTL86
  contact:
    website: 
servers:
  - url: 
    description: Sandbox server (uses test data)
  - url: http://localhost:8501
    description: Localhost server (dev in localhost)
  # - url: https://api.example.com/v1
  #   description: Production server (uses live data)
tags:
  - name: authentication
    description: Access to admin dashboard
paths:
  /auth/login:
    $ref: './components/auth/index.yml#/login'
  /auth/access-token:
    $ref: './components/auth/index.yml#/renewAccessToken'
  /auth/forgot-password:
    $ref: './components/auth/index.yml#/forgotPassword'
  /auth/set-password:
    $ref: './components/auth/index.yml#/setPassword'
  /profile:
    $ref: './components/profile/index.yml'
  /profile/password:
    $ref: './components/profile/other.yml#/setNewPassword'
  /users:
    $ref: './components/users/index.yml'
  /users/{id}:
    $ref: './components/users/id.yml'
  /users/{id}/password:
    $ref: './components/users/other.yml#/resetPassword'
  /roles:
    $ref: './components/roles/index.yml'
  /roles/{id}:
    $ref: './components/roles/id.yml'
  /permissions:
    $ref: './components/roles/other.yml#/getAllPermissions'
  /media:
    $ref: './components/media/index.yml'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
